import type { PlateJurisdiction, RegionId } from "../../shared/types";

export interface PlateTheme {
  foreground: string;
  background: string;
}

type RegionThemes = Record<RegionId, Readonly<Record<string, PlateTheme>>>;

const WHITE = "#f7f7f2";
const BLACK = "#171918";
const NAVY = "#173d68";

/*
 * Representative colors for the current standard passenger plate in the
 * United States, Canada, and Mexico. Scenic/graphic plates use the serial
 * color plus the dominant light field behind it. Europe intentionally uses
 * national colors because most standard plates there are black on white.
 *
 * Sources and maintenance notes live in docs/plate-colors.md.
 */
export const PLATE_THEMES: RegionThemes = {
  us: {
    AL: { foreground: BLACK, background: "#c9e0eb" },
    AK: { foreground: "#1f3a75", background: "#f2c94c" },
    AZ: { foreground: "#20533f", background: "#e8c9a1" },
    AR: { foreground: BLACK, background: "#e8eef1" },
    CA: { foreground: "#17195e", background: WHITE },
    CO: { foreground: "#20533f", background: WHITE },
    CT: { foreground: "#123e67", background: "#c9deeb" },
    DE: { foreground: "#d5b44b", background: "#00305e" },
    DC: { foreground: "#003087", background: WHITE },
    FL: { foreground: "#006747", background: WHITE },
    GA: { foreground: BLACK, background: WHITE },
    HI: { foreground: BLACK, background: WHITE },
    ID: { foreground: BLACK, background: WHITE },
    IL: { foreground: BLACK, background: "#dce9f1" },
    IN: { foreground: "#173d68", background: "#e6e2cf" },
    IA: { foreground: BLACK, background: "#c7ddea" },
    KS: { foreground: BLACK, background: "#d5e4e9" },
    KY: { foreground: "#00205b", background: "#bcdceb" },
    LA: { foreground: "#174a7c", background: WHITE },
    ME: { foreground: "#173d68", background: WHITE },
    MD: { foreground: BLACK, background: WHITE },
    MA: { foreground: "#c8102e", background: WHITE },
    MI: { foreground: "#174a7c", background: WHITE },
    MN: { foreground: BLACK, background: WHITE },
    MS: { foreground: "#00205b", background: WHITE },
    MO: { foreground: "#173d68", background: WHITE },
    MT: { foreground: WHITE, background: "#1f5a91" },
    NE: { foreground: "#173d68", background: WHITE },
    NV: { foreground: BLACK, background: "#bcdceb" },
    NH: { foreground: "#1b4d3e", background: "#e7e4d6" },
    NJ: { foreground: BLACK, background: "#f5d547" },
    NM: { foreground: "#8f1723", background: "#f4c430" },
    NY: { foreground: "#003087", background: WHITE },
    NC: { foreground: "#1f4e9c", background: WHITE },
    ND: { foreground: BLACK, background: "#bfd9e8" },
    OH: { foreground: "#173d68", background: "#e8dcc5" },
    OK: { foreground: WHITE, background: "#b12035" },
    OR: { foreground: "#173d68", background: WHITE },
    PA: { foreground: "#1b3a6b", background: "#f5f0dc" },
    RI: { foreground: "#0b2c5c", background: "#c5ddeb" },
    SC: { foreground: BLACK, background: WHITE },
    SD: { foreground: "#174a7c", background: "#d8e5e8" },
    TN: { foreground: WHITE, background: "#00205b" },
    TX: { foreground: BLACK, background: WHITE },
    UT: { foreground: "#173d68", background: "#d7e2e1" },
    VT: { foreground: WHITE, background: "#006b3c" },
    VA: { foreground: "#1f3d7a", background: WHITE },
    WA: { foreground: "#173d68", background: WHITE },
    WV: { foreground: "#1f3160", background: WHITE },
    WI: { foreground: BLACK, background: WHITE },
    WY: { foreground: WHITE, background: "#182b49" },
  },
  canada: {
    AB: { foreground: "#1b3f8b", background: WHITE },
    BC: { foreground: "#12326e", background: WHITE },
    MB: { foreground: "#003c71", background: WHITE },
    NB: { foreground: "#c8102e", background: WHITE },
    NL: { foreground: "#003da5", background: WHITE },
    NS: { foreground: "#003c71", background: "#f2f2ee" },
    NT: { foreground: "#0033a0", background: WHITE },
    NU: { foreground: BLACK, background: "#bed8e5" },
    ON: { foreground: "#003c71", background: WHITE },
    PE: { foreground: "#007a38", background: WHITE },
    QC: { foreground: "#003da5", background: WHITE },
    SK: { foreground: "#00693e", background: WHITE },
    YT: { foreground: BLACK, background: WHITE },
  },
  mexico: {
    AGS: { foreground: BLACK, background: WHITE },
    BC: { foreground: "#6f263d", background: WHITE },
    BCS: { foreground: "#b3263e", background: WHITE },
    CAM: { foreground: BLACK, background: "#f5ead2" },
    CHP: { foreground: BLACK, background: WHITE },
    CHH: { foreground: "#6f263d", background: WHITE },
    CMX: { foreground: BLACK, background: WHITE },
    COA: { foreground: BLACK, background: WHITE },
    COL: { foreground: "#6f263d", background: WHITE },
    DUR: { foreground: "#6f263d", background: WHITE },
    GUA: { foreground: "#15569a", background: WHITE },
    GRO: { foreground: "#6f263d", background: "#e9d6a4" },
    HID: { foreground: "#6f263d", background: WHITE },
    JAL: { foreground: BLACK, background: WHITE },
    MEX: { foreground: BLACK, background: WHITE },
    MIC: { foreground: "#6f263d", background: WHITE },
    MOR: { foreground: BLACK, background: WHITE },
    NAY: { foreground: BLACK, background: "#e6ead7" },
    NLE: { foreground: BLACK, background: WHITE },
    OAX: { foreground: BLACK, background: "#eee4cf" },
    PUE: { foreground: "#6f263d", background: WHITE },
    QUE: { foreground: "#15569a", background: WHITE },
    ROO: { foreground: BLACK, background: WHITE },
    SLP: { foreground: BLACK, background: "#e8efcf" },
    SIN: { foreground: BLACK, background: WHITE },
    SON: { foreground: BLACK, background: "#ead9b9" },
    TAB: { foreground: BLACK, background: WHITE },
    TAM: { foreground: "#6f263d", background: WHITE },
    TLA: { foreground: "#63345f", background: WHITE },
    VER: { foreground: BLACK, background: WHITE },
    YUC: { foreground: "#14713d", background: WHITE },
    ZAC: { foreground: BLACK, background: "#e7d1aa" },
  },
  europe: {
    AL: { foreground: "#000000", background: "#e41e20" },
    AND: { foreground: "#10069f", background: "#f2cb32" },
    AM: { foreground: NAVY, background: "#f2a800" },
    A: { foreground: "#c8102e", background: WHITE },
    AZ: { foreground: WHITE, background: "#1f6079" },
    BY: { foreground: WHITE, background: "#b42034" },
    B: { foreground: BLACK, background: "#fdda24" },
    BIH: { foreground: "#f7d117", background: "#002f6c" },
    BG: { foreground: "#006a44", background: WHITE },
    HR: { foreground: "#171f69", background: WHITE },
    CY: { foreground: "#a65f28", background: WHITE },
    CZ: { foreground: WHITE, background: "#11457e" },
    DK: { foreground: WHITE, background: "#c8102e" },
    EST: { foreground: "#0072ce", background: WHITE },
    FIN: { foreground: "#003580", background: WHITE },
    F: { foreground: "#002654", background: WHITE },
    GE: { foreground: "#da291c", background: WHITE },
    D: { foreground: BLACK, background: "#ffce00" },
    GR: { foreground: "#0d5eaf", background: WHITE },
    H: { foreground: "#477050", background: WHITE },
    IS: { foreground: WHITE, background: "#02529c" },
    IRL: { foreground: "#006b45", background: "#fffaf0" },
    I: { foreground: "#006b3f", background: WHITE },
    RKS: { foreground: "#f4d03f", background: "#244aa5" },
    LV: { foreground: WHITE, background: "#9e3039" },
    FL: { foreground: "#f3c300", background: "#002b7f" },
    LT: { foreground: "#004f2d", background: "#fdb913" },
    L: { foreground: "#00649a", background: WHITE },
    M: { foreground: WHITE, background: "#cf142b" },
    MD: { foreground: "#003da5", background: "#ffd200" },
    MC: { foreground: WHITE, background: "#ce1126" },
    MNE: { foreground: "#8f1321", background: "#e6b52a" },
    NL: { foreground: WHITE, background: "#21468b" },
    NMK: { foreground: "#9d0000", background: "#f8e92e" },
    N: { foreground: WHITE, background: "#ba0c2f" },
    PL: { foreground: "#dc143c", background: WHITE },
    P: { foreground: "#ffca00", background: "#005c32" },
    RO: { foreground: "#002b7f", background: "#fcd116" },
    RUS: { foreground: "#0039a6", background: WHITE },
    RSM: { foreground: "#286f95", background: WHITE },
    SRB: { foreground: WHITE, background: "#c6363c" },
    SK: { foreground: "#0b4ea2", background: WHITE },
    SLO: { foreground: "#005da4", background: WHITE },
    E: { foreground: "#8f1016", background: "#f1bf00" },
    S: { foreground: "#ffcd00", background: "#005293" },
    CH: { foreground: WHITE, background: "#d52b1e" },
    TR: { foreground: WHITE, background: "#e30a17" },
    UA: { foreground: "#0057b7", background: "#ffd700" },
    UK: { foreground: WHITE, background: "#012169" },
    V: { foreground: "#715700", background: WHITE },
  },
};

const FALLBACK_THEME: PlateTheme = { foreground: NAVY, background: WHITE };

export function plateTheme(plate: PlateJurisdiction): PlateTheme {
  return PLATE_THEMES[plate.region][plate.code] ?? FALLBACK_THEME;
}
